apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: coredns-prometheus
  labels:
    k8s-app: coredns-prometheus
spec:
  selector:
    k8s-app: kube-dns 
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9153
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: coredns
  name: coredns
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: coredns-prometheus

